# Generated by Django 4.2.5 on 2023-09-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasonable_recommendation_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discounted_items',
            name='sales_num',
        ),
        migrations.AlterField(
            model_name='discounted_items',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discounted_items',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
