# Generated by Django 3.2.21 on 2023-09-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasonable_recommendation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
