# Generated by Django 4.2.5 on 2023-09-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasonable_recommendation_app', '0002_remove_discounted_items_sales_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounted_items',
            name='product_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discounted_items',
            name='productimg_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
