# Generated by Django 4.2.5 on 2023-09-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasonable_recommendation_app', '0003_discounted_items_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounted_items',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='discounted_items',
            name='productimg_url',
            field=models.URLField(),
        ),
    ]
