# Generated by Django 4.2.5 on 2023-09-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasonable_recommendation_app', '0004_alter_discounted_items_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounted_items',
            name='productimg_url',
            field=models.URLField(default='www.google.com'),
        ),
    ]
