# Generated by Django 4.2.5 on 2023-09-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasonable_recommendation_app', '0005_alter_discounted_items_productimg_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounted_items',
            name='productimg_url',
            field=models.URLField(),
        ),
    ]
