# Generated by Django 4.2.5 on 2023-09-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reasonable_recommendation_app', '0007_alter_discounted_items_productimg_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discounted_items',
            name='productimg_url',
        ),
    ]
