# Generated by Django 4.2.5 on 2023-09-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasonable_recommendation_app', '0008_remove_discounted_items_productimg_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounted_items',
            name='productimg_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
